# version: '3.8'

# services:
#   backend:
#     image: maven:3.8-openjdk-17
#     container_name: backend
#     ports:
#       - '3001:3001'
#     volumes:
#       - ./projekt_java:/app
#     working_dir: /app
#     command: >
#       sh -c 'mvn clean install && java -jar target/*.jar'

#   mongodb:
#     image: mongo:latest
#     container_name: mongodb
#     ports:
#       - '27017:27017'

#   postgres:
#     image: postgres:latest
#     container_name: postgres
#     ports:
#       - '5432:5432'
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
